---
root: true

env:
  browser: true
  es6: true
  node: true
  jest: true

parser: vue-eslint-parser

parserOptions:
  ecmaVersion: 2019
  sourceType: module

# Rules: https://eslint.org/docs/rules/
# 0 = off
# 1 = warn
# 2 = error
rules:
  # Possible Errors
  for-direction: 2
  getter-return: 1
  no-await-in-loop: 1
  no-compare-neg-zero: 2
  no-cond-assign:
    - 2
    - except-parens
  no-console: 1
  no-constant-condition: 0
  no-control-regex: 1
  no-debugger: 1
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty: 1
  no-empty-character-class: 1
  no-ex-assign: 1
  no-extra-boolean-cast: 1
  no-extra-parens: 0
  no-extra-semi: 2
  no-func-assign: 1
  no-inner-declarations: 0
  no-invalid-regexp: 2
  no-irregular-whitespace: 1
  no-obj-calls: 1
  no-prototype-builtins: 0
  no-regex-spaces: 1
  no-sparse-arrays: 2
  no-template-curly-in-string: 0
  no-unexpected-multiline: 1
  no-unreachable: 2
  no-unsafe-finally: 1
  no-unsafe-negation: 1
  use-isnan: 1
  valid-jsdoc: 0
  valid-typeof: 1
  # Best Practices
  accessor-pairs: 0
  array-callback-return: 1
  block-scoped-var: 0
  class-methods-use-this: 0 # Prefer converting the method into a static function when not using "this"
  complexity: 0
  consistent-return: 0
  curly: 2
  default-case: 1
  dot-location:
    - 1
    - property
  dot-notation: 0
  eqeqeq: 0
  guard-for-in: 0
  max-classes-per-file: 0
  no-alert: 0
  no-caller: 1
  no-case-declarations: 1
  no-div-regex: 0
  no-else-return: 0
  no-empty-function: 1
  no-empty-pattern: 1
  no-eq-null: 1
  no-eval: 0
  no-extend-native: 0
  no-extra-bind: 0
  no-extra-label: 0
  no-fallthrough: 1
  no-floating-decimal: 1
  no-global-assign: 2
  no-implicit-coercion: 0
  no-implicit-globals: 0
  no-implied-eval: 2
  no-invalid-this: 0
  no-iterator: 2
  no-labels: 0
  no-lone-blocks: 1
  no-loop-func: 0
  no-magic-numbers: 0
  no-multi-spaces: 2
  no-multi-str: 2
  no-new: 0
  no-new-func: 0
  no-new-wrappers: 0
  no-octal: 2
  no-octal-escape: 0
  no-param-reassign: 0
  no-proto: 0
  no-redeclare: 2
  no-restricted-properties: 0
  no-return-assign: 1 # Accepted if parenthesis is used
  no-return-await: 0
  no-script-url: 2
  no-self-assign: 1
  no-self-compare: 2
  no-sequences: 1
  no-throw-literal: 0
  no-unmodified-loop-condition: 0
  no-unused-expressions: 0
  no-unused-labels: 1
  no-useless-call: 1
  no-useless-concat: 1
  no-useless-escape: 1
  no-useless-return: 1
  no-void: 1
  no-warning-comments: 0
  no-with: 0
  prefer-promise-reject-errors: 1
  radix: 0
  require-await: 0
  vars-on-top: 0
  wrap-iife: 0
  yoda: 0
  # Strict Mode
  strict: 0
  # Variables
  init-declarations: 0
  no-delete-var: 1
  no-label-var: 1
  no-restricted-globals: 0
  no-shadow: 0
  no-shadow-restricted-names: 2
  no-undef: 1
  no-undef-init: 1
  no-undefined: 2
  no-unused-vars: 1
  no-use-before-define:
    - 1
    - functions: false
      classes: false
      variables: false
  # Node.js and CommonJS
  callback-return: 0
  global-require: 0
  handle-callback-err: 1
  no-buffer-constructor: 0
  no-mixed-requires: 1
  no-new-require: 0
  no-path-concat: 1
  no-process-env: 0
  no-process-exit: 0
  no-restricted-modules: 0
  no-sync: 0
  # Stylistic Issues
  array-bracket-newline: 0
  array-bracket-spacing: 0
  array-element-newline: 0
  block-spacing: 1
  brace-style:
    - 1
    - 1tbs
    - allowSingleLine: true
  camelcase: 0
  capitalized-comments: 0
  comma-dangle: 0
  comma-spacing: 1
  comma-style: 1
  computed-property-spacing: 0
  consistent-this:
    - 1
    - that
  eol-last: 1
  func-call-spacing: 1
  func-name-matching: 0
  func-names: 0
  func-style: 0
  function-paren-newline: 0
  id-blacklist: 0
  id-length:
    - 1
    - min: 1
      max: 30
  id-match: 0
  implicit-arrow-linebreak: 0
  indent:
    - 1
    - 2
  jsx-quotes:
    - 1
    - prefer-double
  key-spacing:
    - 1
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - 1
    - before: true
      after: true
  line-comment-position:
    - 0
    - above
  linebreak-style: 0
  lines-around-comment: 0
  lines-between-class-members: 1
  max-depth: 0
  max-len:
    - 0
    - code: 120
      tabWidth: 2
      ignoreComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  max-lines:
    - 0
    - max: 300
      skipBlankLines: true
      skipComments: true
  max-lines-per-function: 0
  max-nested-callbacks: 0
  max-params: 0
  max-statements: 0
  max-statements-per-line:
    - 0
    - max: 1
  multiline-comment-style:
    - 0
    - bare-block
  multiline-ternary:
    - 1
    - always-multiline
  new-cap: 0
  new-parens: 1
  newline-per-chained-call: 1
  no-array-constructor: 0
  no-bitwise: 0
  no-continue: 1 # Use "if" block instead of "continue"
  no-inline-comments: 0
  no-lonely-if: 1
  no-mixed-operators: 2 # Use parenthesis for expression separation
  no-mixed-spaces-and-tabs: 1
  no-multi-assign: 1
  no-multiple-empty-lines:
    - 1
    - max: 2
      maxBOF: 0 # First empty line of a file count as a line
      maxEOF: 0 # Last empty line of a file does not count as a line
  no-negated-condition: 1
  no-nested-ternary: 0
  no-new-object: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  no-tabs: 1
  no-ternary: 0
  no-trailing-spaces: 1
  no-underscore-dangle: 0
  no-unneeded-ternary: 1
  no-whitespace-before-property: 1
  nonblock-statement-body-position: 0
  object-curly-newline: 0
  object-curly-spacing:
    - 1
    - always
  object-property-newline: 1
  one-var:
    - 1
    - never
  one-var-declaration-per-line: 1
  operator-assignment: 1
  operator-linebreak:
    - 1
    - before
    - overrides: { "=": after }
  padded-blocks:
    - 1
    - never
  padding-line-between-statements: 0
  prefer-object-spread: 1
  quote-props: 0
  quotes:
    - 1
    - single
    - avoidEscape: true
  require-jsdoc: 0
  semi: 2
  semi-spacing: 1
  semi-style: 2
  sort-keys: 0
  sort-vars: 0
  space-before-blocks: 1
  space-before-function-paren:
    - 1
    - never
  space-in-parens:
    - 1
    - never
  space-infix-ops: 1
  space-unary-ops: 1
  spaced-comment: 1
  switch-colon-spacing: 1
  template-tag-spacing: 1
  unicode-bom: 0
  wrap-regex: 1
  # ECMAScript 6
  arrow-body-style: 1
  arrow-parens: 0
  arrow-spacing: 1
  constructor-super: 2
  generator-star-spacing:
    - 1
    - before: false
      after: true
  no-class-assign: 2
  no-confusing-arrow:
    - 2
    - allowParens: true
  no-const-assign: 2
  no-dupe-class-members: 2
  no-duplicate-imports: 1
  no-new-symbol: 2
  no-restricted-imports: 0
  no-this-before-super: 2
  no-useless-computed-key: 1
  no-useless-constructor: 1
  no-useless-rename: 1
  no-var: 1
  object-shorthand: 1
  prefer-arrow-callback: 1
  prefer-const: 1
  prefer-destructuring: 1
  prefer-numeric-literals: 1
  prefer-rest-params: 1
  prefer-template: 0
  require-yield: 2
  rest-spread-spacing: 1
  sort-imports: 0
  symbol-description: 0
  template-curly-spacing: 1
  yield-star-spacing:
    - 1
    - before: false
      after: true
